/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateboardImport } from './routes/createboard'
import { Route as CreatenoteFromBoardImport } from './routes/createnote.$fromBoard'
import { Route as BoardBoardImport } from './routes/board.$board'
import { Route as BoardBoardNotesImport } from './routes/board.$board.notes'
import { Route as BoardBoardChatChatImport } from './routes/board.$board.chat.$chat'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const AuthActionLazyImport = createFileRoute('/auth/$action')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const CreateboardRoute = CreateboardImport.update({
  path: '/createboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthActionLazyRoute = AuthActionLazyImport.update({
  path: '/auth/$action',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth.$action.lazy').then((d) => d.Route))

const CreatenoteFromBoardRoute = CreatenoteFromBoardImport.update({
  path: '/createnote/$fromBoard',
  getParentRoute: () => rootRoute,
} as any)

const BoardBoardRoute = BoardBoardImport.update({
  path: '/board/$board',
  getParentRoute: () => rootRoute,
} as any)

const BoardBoardNotesRoute = BoardBoardNotesImport.update({
  path: '/notes',
  getParentRoute: () => BoardBoardRoute,
} as any)

const BoardBoardChatChatRoute = BoardBoardChatChatImport.update({
  path: '/chat/$chat',
  getParentRoute: () => BoardBoardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/createboard': {
      preLoaderRoute: typeof CreateboardImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/board/$board': {
      preLoaderRoute: typeof BoardBoardImport
      parentRoute: typeof rootRoute
    }
    '/createnote/$fromBoard': {
      preLoaderRoute: typeof CreatenoteFromBoardImport
      parentRoute: typeof rootRoute
    }
    '/auth/$action': {
      preLoaderRoute: typeof AuthActionLazyImport
      parentRoute: typeof rootRoute
    }
    '/board/$board/notes': {
      preLoaderRoute: typeof BoardBoardNotesImport
      parentRoute: typeof BoardBoardImport
    }
    '/board/$board/chat/$chat': {
      preLoaderRoute: typeof BoardBoardChatChatImport
      parentRoute: typeof BoardBoardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CreateboardRoute,
  AboutLazyRoute,
  BoardBoardRoute.addChildren([BoardBoardNotesRoute, BoardBoardChatChatRoute]),
  CreatenoteFromBoardRoute,
  AuthActionLazyRoute,
])

/* prettier-ignore-end */
