// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "board.proto" (package "proto.board", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BoardService } from "./board";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Empty } from "./google/protobuf/empty";
import type { CreateBoardRequest } from "./board";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service proto.board.BoardService
 */
export interface IBoardServiceClient {
    /**
     * @generated from protobuf rpc: createBoard(proto.board.CreateBoardRequest) returns (google.protobuf.Empty);
     */
    createBoard(input: CreateBoardRequest, options?: RpcOptions): UnaryCall<CreateBoardRequest, Empty>;
}
/**
 * @generated from protobuf service proto.board.BoardService
 */
export class BoardServiceClient implements IBoardServiceClient, ServiceInfo {
    typeName = BoardService.typeName;
    methods = BoardService.methods;
    options = BoardService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: createBoard(proto.board.CreateBoardRequest) returns (google.protobuf.Empty);
     */
    createBoard(input: CreateBoardRequest, options?: RpcOptions): UnaryCall<CreateBoardRequest, Empty> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateBoardRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
