// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "chat.proto" (package "proto.chat", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ChatService } from "./chat";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ChatResponse } from "./chat";
import type { ChatRequest } from "./chat";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service proto.chat.ChatService
 */
export interface IChatServiceClient {
    /**
     * @generated from protobuf rpc: getAllMessages(proto.chat.ChatRequest) returns (proto.chat.ChatResponse);
     */
    getAllMessages(input: ChatRequest, options?: RpcOptions): UnaryCall<ChatRequest, ChatResponse>;
}
/**
 * @generated from protobuf service proto.chat.ChatService
 */
export class ChatServiceClient implements IChatServiceClient, ServiceInfo {
    typeName = ChatService.typeName;
    methods = ChatService.methods;
    options = ChatService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: getAllMessages(proto.chat.ChatRequest) returns (proto.chat.ChatResponse);
     */
    getAllMessages(input: ChatRequest, options?: RpcOptions): UnaryCall<ChatRequest, ChatResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChatRequest, ChatResponse>("unary", this._transport, method, opt, input);
    }
}
