// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "chat.proto" (package "proto.chat", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MessageService } from "./chat";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { MessageResponse } from "./chat";
import type { MessageRequest } from "./chat";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service proto.chat.MessageService
 */
export interface IMessageServiceClient {
    /**
     * @generated from protobuf rpc: getAllMessages(proto.chat.MessageRequest) returns (proto.chat.MessageResponse);
     */
    getAllMessages(input: MessageRequest, options?: RpcOptions): UnaryCall<MessageRequest, MessageResponse>;
}
/**
 * @generated from protobuf service proto.chat.MessageService
 */
export class MessageServiceClient implements IMessageServiceClient, ServiceInfo {
    typeName = MessageService.typeName;
    methods = MessageService.methods;
    options = MessageService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: getAllMessages(proto.chat.MessageRequest) returns (proto.chat.MessageResponse);
     */
    getAllMessages(input: MessageRequest, options?: RpcOptions): UnaryCall<MessageRequest, MessageResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<MessageRequest, MessageResponse>("unary", this._transport, method, opt, input);
    }
}
